font:
  size: 13
  # normal:
  #   family: Meslo LG M DZ for Powerline
  # bold:
  #   family: Meslo LG M DZ for Powerline
  # italic:
  #   family: Meslo LG M DZ for Powerline
  #     #colors:
  primary:
    background: '0x002b36'
    foreground: '0x839496'
  cursor:
    text: '0x002b36'
    cursor: '0x839496'
key_bindings:
  - { key: A, mods: Alt, chars: "\x1ba" }
  - { key: Key1, mods: Alt|Command, command: { program: "open", args: ["/Applications/Google\ Chrome.app"] } }
  - { key: Key3, mods: Alt|Command, command: { program: "open", args: ["/Applications/iTerm.app"] } }
